### PR TITLE
Add TLS support using Let's Encrypt

### LINKED ISSUE #2: Add TLS support using Let's Encrypt
I notice it is on your TODO list, but thought I'd create an issue to raise my hand and say "I will take a stab at implementing it". It is the missing part for this project to be really interesting for my use.

### PR DESCRIPTION
**Pull request by bep**
This commit also changes the configuration so it is now possible to define multiple hosts.

TLS is enabled by setting `TLSCertificateDir`. 

Note that for this to work, you will also want to set the `Listen` config option to `:https`.

Fixes #2

### CODE REVIEW

**Comment by bep** [comment]
This obviously needs a couple of lines in the README, but I thought I'd open a PR to see if we agree on the implementation. I have tested it with some domain/bucket combos, and it works very well.

**Comment by alexandres** [comment]
Fantastic work @bep! I'm really impressed. Thank you so much for this. This commit solves the lack of TLS and adds important new functionality.

3 comments:

1. in cache.go#L135 in the host lookup will fail if a host is not found. Might it be more interesting to fall back to the first defined host? This is how Apache and NGINX handle vhosts if no host match is found. The downside to the Apache way is that it could produce unexpected behavior if a user mispells a Host and the request falls back to the first Host. Maybe logging to stderr could help here to indicate that the fallback is occurring. 

2. You kept the default S3 config option in config.json but in #7 you had suggested removing this, keeping only ENV configuration and the per-Host override. That suggestion seemed like a  good idea but I also like the way you did it here: use config.json value if specified else fallback to environment. Perhaps specifying both should throw a fatal error to ensure a user does it one way or the other?

3. Rather than have the Cache.Read retrieve the StorageProvider by using CacheClient.host, might it not be better to inject a StorageProvider in the Cache.Read method? This way the Host decision logic rests entirely in handler.go. Right now there is some logic in handler.go for the Delete methods, and some in cache.go for the Read methods.

**Comment by alexandres** [comment]
> This obviously needs a couple of lines in the README, but I thought I'd open a PR to see if we agree on the implementation. I have tested it with some domain/bucket combos, and it works very well.

I'd be glad to write this. I've never tried this but is it possible to pull your PR branch, add another commit, and merge without you losing credit? Else I'll merge this and add another commit with the README changes.

**Comment by bep** [comment]
>I'd be glad to write this. I've never tried this but is it possible to pull your PR branch, add another commit.

You can just add commits to this branch. That works fine. GitHub has created some magic there. But my guess is the README can wait "some hours". I will look at your comments tomorrow.

**Comment by bep** [comment]
But as this is a software "in progress", so to speak, you might as well merge my PR and do your changes/additions in master -- and I'm happy to discuss any further changes/improvements in another issue.

**Pull request merged**
